function printResults(results)
% print out results
fprintf('optimized quantity                 | optimal value | optimal voxel width\n');
fprintf('-----------------------------------+---------------+--------------------\n');
fprintf('univariate detection probability   | %.2f          | %.2f mm            \n',...
    results.pDetectUnivariate_max,results.pDetectUnivariate_optW);
fprintf('multivariate detection probability | %.2f          | %.2f mm            \n',...
    results.pDetectMultivariate_max,results.pDetectMultivariate_optW);
fprintf('decoding probability - 2 classes   | %.2f          | %.2f mm            \n',...
    results.pDecode2_max,results.pDecode2_optW);
fprintf('decoding accuracy    - 2 classes   | %.2f          | %.2f mm            \n',...
    results.accuracyDecode2_max,results.accuracyDecode2_optW);
fprintf('decoding probability - 4 classes   | %.2f          | %.2f mm            \n',...
    results.pDecode4_max,results.pDecode4_optW);
fprintf('decoding accuracy    - 4 classes   | %.2f          | %.2f mm            \n',...
    results.accuracyDecode4_max,results.accuracyDecode4_optW);
fprintf('decoding probability - 8 classes   | %.2f          | %.2f mm            \n',...
    results.pDecode8_max,results.pDecode8_optW);
fprintf('decoding accuracy    - 8 classes   | %.2f          | %.2f mm            \n',...
    results.accuracyDecode8_max,results.accuracyDecode8_optW);
fprintf('pattern correlation                | %.2f          | %.2f mm            \n',...
    results.patternCorrelation_max,results.patternCorrelation_optW);
end